### ISSUE TITLE
Comparison against other methods

### ISSUE THREAD

**Issue by MTDzi** [robot-learning-freiburg/CL-SLAM#1]
Awesome work, thank you for your contribution.

I was wondering, have you guys considered comparing CL-SLAM against another deep learning approach, e.g. https://github.com/princeton-vl/DROID-SLAM ?

**Comment by vniclas** [comment]
Hi @MTDzi,
I'm sorry for the delayed reply. In a recent update, we compared CL-SLAM against [DeepSLAM](https://ieeexplore.ieee.org/document/9047170) and monocular [ORB-SLAM](https://github.com/raulmur/ORB_SLAM2). We will update the arxiv paper within the next few days.
